
# blowfish configs
colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = false

[homepage]
 layout = 'card'
 homepageImage = "logos/istrum-logo-mod.png"
 layoutBackgroundBlur = true

[list]
  showSummary = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showTableOfContents = true

